import type { Metadata } from "next"
import ScreenLoader from "./components/ScreenLoader"
import { geistMono, geistSans } from "./fonts"
import "./globals.css"
import Header from "./layouts/Header"

export const metadata: Metadata = {
  title: "MotionScape",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScreenLoader />
        <Header />
        {children}
      </body>
    </html>
  )
}
